# fly.toml app configuration file generated for bloglistcicd on 2024-04-17T20:57:17+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bloglistcicd'
primary_region = 'nrt'

[build]

[env]
  PORT = '3000'

[processes]
  app = 'node backend/index.js'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
